### PR TITLE
Fix UTF8 upper/lower/sentence/title case

### LINKED ISSUE #13: Change Case
Currently PecoRename only allows UPPERCASE/lowercase . 
Few more case like : 
Sentence case
Title Case
tOGGLE cASE could be added .

### PR DESCRIPTION
**Pull request by janus2**
* Fix upper and lower case. They work much better.
* Introduce sentence and title case not sure if this is correct
  Please if you know exotic languages test and let me know
* Thanks to Pulkomandy for let me know the class UnicodeChar
* Fixes #13

### CODE REVIEW

**Comment by janus2** [comment]
@humdingerb Does the wording for this renamer looks good to you? I think this app is pretty solid now...

**Comment by humdingerb** [comment]
For the specific  UPPER/lower? Looks fine!

**Comment by janus2** [comment]
I have added:
Sentence case
Title Case

or is better
Capitalize
Capitalize Each Word

**Comment by humdingerb** [comment]
I think the naming is OK.
"Sentence case" should capitalize the first letter though. It doesn't right now. Should I file an issue. :)

**Pull request merged**
