### PR TITLE
Remove renamer works in all direction combinations (probably)

### LINKED ISSUE #43: Remove renamer should work in all direction combinations
Hope I explain it clearly...
Only the following "Example 4" works as expected in all directions. The rest has issues.
(I cannot bend my little brain around the code, but at least I can try to describe what is and what should be...)

**Example 1: both from left**
> "Remove characters from position" "0" "from the front (left)"
> "to position" "3" "from the front (left)"

Works: It removes the first 3 chars, the filename "template" becomes "plate"
_If you switch the 0 and 3, it should be the same, but that doesn't work (preview empty)._

**Example 2: both from right**
> "Remove characters from position" "3" "from the back (right)"
> "to position" "0" "from the back (right)"

Works: It removes the last 3 chars, the filename "template" becomes "templ"
_If you switch the 0 and 3, it should be the same, but that doesn't work (preview empty)._

**Example 3: right to left**
> "Remove characters from position" "3" "from the back (right)"
> "to position" "0" "from the front (left)"

_Doesn't work.  The filename "template" should become "ate" (preview empty).
If you switch the 0 and 3, "template" should become "tem", but doesn't (preview empty)._

**Example 4: left to right**
> "Remove characters from position" "3" "from the front (left)"
> "to position" "0" "from the back (right)"

Works:  It removes the last 4 chars, the filename "template" becomes "temp".
If you switch the 0 and 3 it works, too: "template" becomes "ate", look:

renamer_remove

### PR DESCRIPTION
**Pull request by janus2**
- Fixes #43
- Needs regression tests

### CODE REVIEW

**Comment by humdingerb** [comment]
Nicely done! I was messing around with re-implementing the whole thing with BStrings, but always had some weird off-by-one errors cropping up... I'm glad you found a simple solution!

I re-did the tests I put in #43 and did some more, and it looks like it's working fine. Your comment there is correct:

> If I am not wrong the example 4 the results should be "tem" and "ate".

"temp" would be wrong. Let's merge! Thanks!

**Comment by humdingerb** [comment]
@janus

This is very strange. I tested it all and it worked fine. Now, whenever I build, it doesn't work at all ("Preview" stays empty) 9 of 10 times.   o_O

I think the whole SetMaxValue() business with:

```
int32 positionMaxValue = 0;
.
.
.
		if (LengthOfFilename > positionMaxValue)
			positionMaxValue = LengthOfFilename;

		fPosition->SetMaxValue(positionMaxValue);
```

in "Remove" and "InsertOverwrite" may be stupid. If you have a list of files to process, the MaxValue keeps changing. Why set one at all?
I saw an issue with the "InsertOverwrite" that you couldn't move the "insert-point" beyond the MaxValue of the shortest filename. I commented out the above quoted code, recompiled, didn't work anymore. Uncommented again, doesn't work anymore either.
Am I going mad?

**Comment by janus2** [comment]
Try with my last commit... could be that! You change parameters but it uses the one in Search and replace. Let me know!

**Comment by humdingerb** [comment]
Thanks, that did it! :)
BTW, what do you think of joining #haiku-3rdparty on IRC. It's very low traffic, and it would be a nice way to quickly contact you.

I also fixed the SetMaxValue() issue I mentioned. Will commit momentarily. Or should I do a PR, so you can intervene? :)

**Comment by janus2** [comment]
You can commit your changes, we can always fix the problems in post-production ;-)

**Comment by janus2** [comment]
Unfortunately, I cannot spend a lot of time on IRC, but if we need to discuss some problems I'll be glad to participate. If you need me just leave a comment on any applications. I will respond ASAP.

**Pull request merged**
