### PR TITLE
PecoRename: Add README and Screenshot of the application

### PR DESCRIPTION
**Pull request by talnacialex**
Hello! This is a Google Code-in Task! I was told to send a pull request to add these two files. Thank you!

### CODE REVIEW

**Comment by humdingerb** [comment]
janus did some nice work recently that changed the GUI a bit. Please build PecoRename from source and take a screenshot of that. Make sure to show the app in action, i.e. after adding some files and setting a rename pattern that shows the new names in the preview column.

In the text, add the available rename modes (the ones from the pop-up menu) as a markdown formatted bullet list.

**Comment by talnacialex** [comment]
I can't compile, because i'm having some issues with my linux computer... I tried to use the version that it's present on HaikuDepot.

**Comment by talnacialex** [comment]
I added now in the readme the modes.

**Comment by humdingerb** [comment]
OK. But having an outdted screenshot doesn't make  much sense either...
How about quickly do the "Run Haiku" GCI task and compile from there?

**Comment by talnacialex** [comment]
I have Haiku installed... I did the GCI task. I will try to see how to compile it, because it's my first time using Haiku... I'm quite pleased with it...

**Comment by humdingerb** [comment]
Cool! Head over to the #haiku IRC channel if you need help. Haiku's IRC client is called "Vision" (see under Applications in the Deskbar).

**Comment by humdingerb** [comment]
Thanks!

**Comment by scottmc** [comment]
Nicely done.  You think a task is easy, just take a screenshot and update the readme, but along the way you learn how to compile apps on Haiku. ;)
Glad you are likely it so far.

**Pull request merged**
