### PR TITLE
Remove useless alert

### PR DESCRIPTION
**Pull request by janus2**

### CODE REVIEW

**Comment by janus2** [comment]
@humdingerb  let me know if it is humdingerb compliant ;-)

**Comment by humdingerb** [comment]
Looks good. If there were conflicts, it'd still be preferred to have a scroll list of the skipped files in a regular window, than the "I marked entries red" alert. Looking for the red entries may be inconvenient for a large list. Using a text view that allows copy&pasting may be useful too (or even a "Save conflict report" if anyone wants to get fancy...).

And hey, those are just my suggestions up for discussion. You, doing the work, are in control. :)

**Comment by janus2** [comment]
I don't know for a separate window with the conflicts. if I use the application my goal is to rename the files if there are conflicts I check before the renaming and try to solve it (The second alert help in this sense, but we have the statusview). I can alway remove the conflicts with the canc button. My 2 dollars or are cents

**Comment by humdingerb** [comment]
It's more about the conflicts that may crop up unexpectedly, i.e. which were not visible in red in the preview before. This can happen if the conflicting files are not part of the list of files that are to be processed.

Anyway, you might be right... :)
Let's keep that one alert and see if there's feedback in the future. I may change the wording though, once you and our GCI buddies give the code a rest for a while. :)
Thanks for your work!

**Comment by janus2** [comment]
> It's more about the conflicts that may crop up unexpectedly, i.e. which were not visible in red in the preview before. This can happen if the conflicting files are not part of the list of files that are to be processed.

It is alert 3, not 2 that informs the user.

> Anyway, you might be right... :)

I'm always right :-P

> Let's keep that one alert and see if there's feedback in the future. I may change the wording though, 

Give me sometimes to think what is the best solution. Maybe I implement the final window because alert 2 informs of the already detected duplicates and 3 informs of disk duplicates.
If you are afraid of "the conflicts that may crop up unexpectedly" 2 does not help.

>once you and our GCI buddies give the code a rest for a while. :)

When does the GCI end? I want to see "weather" out on the streets...

>Thanks for your work!

It's my job, wait... no, it isn't :-D

**Comment by humdingerb** [comment]
GCI finishes (for the students) on Jan 17th. We're counting the days... :)

I've lost track what's alert 1,2,3,4. I trust you know what you're doing... :)
Here's what I'd consider least annoying:
* No alert for the conflicts found to show the preview. Red highlight and status bar update is already enough.
* Only show a window/alert when conflicts popped up while renaming, which were not expected from generating the preview.

Two ideas:
1. Easy - colour the "duplicate" in the status bar red if > 0. This should drag a bit of attention.
2. Harder - the items of the status bar could trigger a filter, so if you e.g. click on the "duplicate" item, it shows like a pressed down button and the list will only show all the conflicting rows. This would be handy if you deal with a lot files in the list.

**Pull request merged**
