### PR TITLE
Cleanup the gui add some check functions

### PR DESCRIPTION
**Pull request by janus2**
* I have  implemented a n log n duplicates check is not active now
* I don't know how to best use the checking
* This is a raw version need a lot of improvements

### CODE REVIEW

**Comment by janus2** [comment]
@humdingerb let me know what you think... There are no checks at the moment, we must decide how to show the user the dups, the old version just turned the preview red.

**Comment by humdingerb** [comment]
Unless anyone can come up with a better solution, I don't see why this wouldn't suffice for now.
If there is a conflict, highlight the preview red and maybe add a tool tip that says:

>   Can't rename '%file%' to '%newfilename%'.
  A file with that name already exists.

Can it happen that within a renaming-session such a conflict can arise that wasn't detected for the preview? If so, the above tool tip could become an alert popping up when it's encountered:

>  Conflict
  Can't rename '%file%' to '%newfilename%'.
  A file with that name already exists.
									OK

**Comment by janus2** [comment]
It works already in this way I don't know if the alerts are different in the phrasing.
The user can suppress the messages and at the and the not renamed name are in red with an alert that specify that.

**Comment by janus2** [comment]
I don't think there is a better solution...

**Comment by humdingerb** [comment]
There are just too many alerts popping up... :)
Why alerts at all, as long as the preview gets red-highlighted (with a tool tip)? This will indicate, that these renamings won't be executed because they conflicted.

**Comment by janus2** [comment]
You can have a conflict with a file on disk that you have not loaded into the application.
This is found only during the renaming. In many ways this is a marginal problem, when renaming in the real world it is improbable to choose the same name. The numbering and case renamer it almost impossible. The alert works in this way now:
1) Caution warning you are renaming the files... if everything is ok this is the only alert you will see
2) The app has found some duplicates the alert informs you there will be problem.
3) During renaming there is a duplication the alert informs you and ask if you want suppress other messages
4) if 2 or 3 are true the red alert tells you that the failed new name are in red.

In the normal use case only 1 should appear.

**Comment by janus2** [comment]
The statusview should help the user to see if there are any duplicates

**Comment by janus2** [comment]
Another approach is to change 2 from there will be blood to I found some duplicates I will skip to rename those file do you want to proceed. Then we skip the marked names... 3 and 4 remain the same.

**Comment by humdingerb** [comment]
With this kind of "session", I see loads of alerts. :)

pecorename


> 1. Caution warning you are renaming the files... if everything is ok this is the only alert you will see

Shouldn't we remove this one? I think it's only annoying. It's the purpose of the tool; I pressed "Rename", I want stuff to change names...

> 2. The app has found some duplicates the alert informs you there will be problem.

That's when showing the preview, right?
Not needed, I'd say, just colour the rows red and update the status.

> 3. During renaming there is a duplication the alert informs you and ask if you want suppress other messages

Not ideal. If there were conflicts and some files couldn't be renamed, having it after the renaming session has finished as a sort of summery, would be nicer. Nothing much the user can do anyway...

>4. if 2 or 3 are true the red alert tells you that the failed new name are in red.

Which I'll be aware of after it popped up for the first time. Every following time it's an annoying alert. I think people will get that the red entries have failed. (-> tool tip?)

**Comment by janus2** [comment]
I think 1 is for legal purpose only...
This is what you are suggesting:
remove 1, remove 2, and skip to rename the file marked in red, if there is a problem don't show 3, show 4 with in red the files that are not renamed.
Am  I correct?

**Comment by janus2** [comment]
About your screenshot you want to use pecorename to give your files meaningful names. I doubt you want remove all the 2 in the filenames (I think this is not a real case).

**Comment by humdingerb** [comment]
> This is what you are suggesting:
> remove 1, remove 2, and skip to rename the file marked in red, if there is a problem don't 
> show 3, show 4 with in red the files that are not renamed.

I think that's it. Only show a summary alert at the end of the renaming session with the list of skipped files. 

> About your screenshot you want to use pecorename to give your files meaningful names. I doubt you want remove all the 2 in the filenames (I think this is not a real case).

Hey, don't assume to imagine all the weird things people may want to do  :)

**Pull request merged**
