### PR TITLE
Doesn't replace files when using drag and drop

### LINKED ISSUE #9: File replace on drag and drop
When you try to add file using drag & drop feature the existing file is replaced with file you drop .

### PR DESCRIPTION
**Pull request by R4H33M**
Fixes #9

### CODE REVIEW

**Comment by humdingerb** [comment]
*  drag'n'drop two files from one location
* drag'n'drop two other files from another location

--> Only the last two files show the correct preview (e.g. with "Insert/overwrite") and are renamed when clicking "Rename".

**Comment by R4H33M** [comment]
Fixed!

**Comment by humdingerb** [comment]
Preview works, the actual renaming still only works on the last dropped files. Please test your changes before updating the PR. :)

**Comment by R4H33M** [comment]
I test extensively before I push, and only push when I am satisfied it works as it should.
> the actual renaming still only works on the last dropped files. 

It works here. I'm testing on x64, what are using?

**Comment by scottmc** [comment]
Please also check it out on a 32 bit Haiku, you can do this in a VM, it only take 3 minutes or so to get a new VM up and running. ;)

**Comment by humdingerb** [comment]
> It works here. I'm testing on x64, what are using?

32bit here. A PecoRename built with gcc8 by doing a "setarch x86" crashes when dropping files:
https://linx.li/pecorename-1850-debug-17-01-2020-05-35-35.report

**Comment by R4H33M** [comment]
> Please also check it out on a 32 bit Haiku, you can do this in a VM, it only take 3 minutes or so to get a new VM up and running. ;)

Sorry, and good point. I will be testing on both now. 
But... there is no issues with renaming on x86 for me. It runs as it should.

**Comment by humdingerb** [comment]
Have you tried renaming files in different folders? That's not working here (32bit, gcc2).
I take 4 files from one folder, 4 from another and "Add file extension". only the second 4 files get renamed. Plus a Report window pops up showing the first 4 files with "Unknown error".

**Comment by janus2** [comment]
If I remember correctly it's not so simple to add this feature, all the internals assume that the files are in the same directory and the gui does the same. I can be wrong it be so long...

**Comment by scottmc** [comment]
So is the original issue solved with this PR, partially solved, or nothing new?  Should we merge the new code or wait for a full solution which handles the files from different directories issue?  Perhaps merge and add new issue?

**Comment by janus2** [comment]
This doesn't work at all, the user can add files from different folders but the application doesn't rename the files properly. To implement this feature the app needs major work.

**Comment by janus2** [comment]
This doesn't work at all, the user can add files from different folders but the application doesn't rename the files properly. To implement this feature the app needs major work.

**Comment by R4H33M** [comment]
> To implement this feature the app needs major work.

Should this PR be shelved for the moment then?

**Comment by humdingerb** [comment]
> Should this PR be shelved for the moment then?

I think so, except you got a major brainwave and can make it work. :)

**Comment by R4H33M** [comment]
Alright. I think we should shelve it - I'll come back to it one day in the near future.

Thanks everyone!

**Comment by humdingerb** [comment]
Thanks for your work so far! I think we should keep this PR open as it should be a first step to solving the issue.

**Comment by scottmc** [comment]
Shelving this one.  It's here to come back to if there is anything worth using here.

**Pull request closed without merging**
