### PR TITLE
TextField liveupdate

### PR DESCRIPTION
**Pull request by janus2**
It feels too unnatural to insert text and don't see changes... and I always forget to press return.
Tested with hundreds of files works fine.
Let me know if you have problems.

### CODE REVIEW

**Comment by humdingerb** [comment]
Seems to work very well! Thanks!

**Comment by janus2** [comment]
I just found that the original implemented a LiveTextControl to do that...
The code had a lot of problems, the duplicate function now doesn't work at all, in the past sometimes depending on the weather. With a lot of file the 1/2 O(n^2) is too expensive and there is the case where a file on the disk already has that name. I think the best we can do is start the conversion and mark the unsuccessful changes (how I don't know, the red... is out of fashion).

I almost went crazy but I found the cause of the drawing glitches. 
I keep the answer for myself. If tonight I die, it will remain uncovered forever...

Just kidding if I die tell axeld it's the BTextView is always the BTextView issue https://dev.haiku-os.org/ticket/3037#comment:25

**Comment by humdingerb** [comment]
>  ...there is the case where a file on the disk already has that name. I think the best we can do is start the conversion and mark the unsuccessful changes (how I don't know, the red... is out of fashion).

If the file already has the 'new' name, everything's great anyway. No need to point it out.
If the filename doesn't match the 'search' string when it comes to renaming, not renaming is the right thing, too. Still no need to point it out(?)

> I almost went crazy but I found the cause of the drawing glitches.
> Just kidding if I die tell axeld it's the BTextView is always the BTextView issue https://dev.haiku-os.org/ticket/3037#comment:25

Oh, that BTextView is a handful, isn't it?
Got a fix too?  :)

**Comment by janus2** [comment]
> If the file already has the 'new' name, everything's great anyway. No need to point it out.
If the filename doesn't match the 'search' string when it comes to renaming, not renaming is the right thing, too. Still no need to point it out(?)

I see two problem:
1) The user can give the same name to different files:
same name different files
So it will rename the first and give errors to the others.
2) The user can give the same name to a file on the drive but not in the app
same name file on disk
It will give the error B_FILE_ALREADY_EXIST.

> Oh, that BTextView is a handful, isn't it?
Got a fix too? :)

Yes, I will never use a BTextView and related classes again.

**Comment by humdingerb** [comment]
oh. yeah, I got a headache and will try to think ybout it tomorrow... :)

>> Oh, that BTextView is a handful, isn't it?
>> Got a fix too? :)

> Yes, I will never use a BTextView and related classes again.

Good fix. :P

**Comment by janus2** [comment]
protopack

**Comment by janus2** [comment]
Let's do it! could be "Rename"

**Comment by humdingerb** [comment]
And the status: "Idle"

WRT to conflicting filenames, I still have to think about it more. Maybe the "Conflict" solution from "Filer" can be an inspiration. Or being lazy, just highlight the row reddish and have a tool tip tell the user what's the issue and let him deal with it on his own...

**Comment by janus2** [comment]
What do you mean whit the status Idle?

**Comment by janus2** [comment]
I turn the point of no return...
point of no return

**Comment by humdingerb** [comment]
> What do you mean whit the status Idle

Instead of the "Awaiting your instructions...".

I like your changes.

**Comment by janus2** [comment]
Just pushed the changes on my branch needs a lot of works, I wrote a n log n dup check but i don't know how to use it.

**Pull request merged**
